neos/Neos.NeosIo

Packages/Sites/Neos.NeosIo/Classes/Neos/NeosIo/TypoScript/RtdLibraryImplementation.php, Packages/Sites/Neos.NeosIo/Classes/Neos/NeosIo/TypoScript/RtdProjectImplementation.php, Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.yaml, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/RtdLibrary.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/RtdProject.html, Packages/Sites/Neos.NeosIo/Resources/Private/TypoScripts/Library/NodeTypes.ts2
The "Documentation Library" can be used to show all projects of a given
user on readthedocs.org.
The "Project Documentation" element can be used to show a single
projects' documentation.
=> [FEATURE] Add documentation content elements

composer.lock
- Fix pagination
- Fix cache issue
- Improve sorting
- Show last version number in search result
=> TASK: Update MarketPlace to 0.1.7

Packages/Sites/Neos.NeosIo/Resources/Private/JavaScript/index.js, Packages/Sites/Neos.NeosIo/Resources/Public/JavaScript/Bundle.min.js, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css, composer.lock
Don't forget to test the package repository (performance improvements):
flow marketplace:sync --force
flow nodeindex:build
See https://github.com/neos/Neos.MarketPlace/pull/15 for more details
=> TASK: Update Neos 2.2.3 + MarketPlace 0.1.10

Packages/Sites/Neos.NeosIo/package.json
added missing npm dependencies for
* get-closest
* in-viewport
=> [BUGFIX] added missing dependencies to package.json

Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/Partials/Image.html
=> BUGFIX: Show image caption when not in edit mode

Packages/Sites/Neos.FlowNeosIo/Resources/Private/Templates/Page/Partials/SiteFooter.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/Page/Partials/SiteFooter.html
=> TASK: Remove JIRA / add status page link in footer

Configuration/Routes.yaml, Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.Stage.yaml, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/Quote.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/Stage.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/TypoScriptObjects/FooterMenu.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/TypoScriptObjects/Menu.html, Packages/Sites/Neos.NeosIo/Resources/Private/TypoScript/NodeTypes/Image.ts2, Packages/Sites/Neos.NeosIo/Resources/Private/TypoScript/NodeTypes/Quote.ts2, Packages/Sites/Neos.NeosIo/Resources/Private/TypoScript/NodeTypes/Stage.ts2
* Enables sitemap.xml
* Adds title attribute to menu links
* Adds title and alt attributes to most images
=> TASK: Basic SEO improvements

Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Organisms/_OffCanvas.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Organisms/_SiteHeader.scss, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css, Packages/Sites/Neos.NeosIo/npm-debug.log
=> BUGFIX: Adjust media queries to bigger navigation

Packages/Application/Neos.NeosIo.Event/Resources/Private/Templates/Page/Partials/SiteFooter.html, Packages/Sites/Neos.FlowNeosIo/Resources/Private/Templates/Page/Partials/SiteFooter.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/Page/Partials/SiteFooter.html
Link uses https, but needs to be http.
resolve #140
=> Fix incorrect link to Crowdin in footer

Packages/Application/Neos.NeosIo.Event/Configuration/NodeTypes.Person.yaml, Packages/Application/Neos.NeosIo.Event/Configuration/NodeTypes.Speaker.yaml, Packages/Application/Neos.NeosIo.Event/Resources/Private/Templates/NodeTypes/Speaker.html, Packages/Application/Neos.NeosIo.Event/Resources/Private/TypoScript/NodeTypes/Speaker.ts2, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Main.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Molecules/_Table.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Organisms/_Speaker.scss, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css
Adds a content collection to the speaker pages to be able to add individual content below the basic information.
Next comping features: Schedule nodetypes and connection between schedule and speaker for dynamic linking.
=> FEATURE: Event package: Add basic speaker page and table styling

.gitignore, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Atoms/_Base.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Molecules/_Media.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/TypoScriptObjects/PostShort.html, Packages/Sites/Neos.NeosIo/Resources/Public/JavaScript/Bundle.min.js, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css
Makes image always full width and
gives article more space on mobile.
Relates: #121
=> BUGFIX: Improve short article layout

Packages/Application/Neos.NeosIo.Event/Configuration/NodeTypes.Speaker.List.yaml, Packages/Application/Neos.NeosIo.Event/Configuration/NodeTypes.Speaker.yaml, Packages/Application/Neos.NeosIo.Event/Resources/Private/Templates/NodeTypes/Partials/Speaker.List.Item.html, Packages/Application/Neos.NeosIo.Event/Resources/Private/Templates/NodeTypes/Speaker.List.html, Packages/Application/Neos.NeosIo.Event/Resources/Private/TypoScript/NodeTypes/Speaker.List.ts2
ToDo content-wise after deployment:
- Add "type of talk" property values to each speaker
- Add "N.N. Speaker", if still needed
=> FEATURE: Add speaker list

Packages/Sites/Neos.NeosIo/Resources/Private/Translations/en/Main.xlf
=> BUGFIX: Add missing label for subscription badge

Packages/Sites/Neos.NeosIo/Classes/Neos/NeosIo/Aspects/CacheBusterAspect.php
Adds an aspect providing sha1 based
cache busting for resource uris.
Resolves: #136
=> TASK: Add cache busting for assets

.beach.yaml
=> TASK: Minify css and js in production

Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.Badge.yaml, Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.BadgeGrid.yaml, Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.SemanticSection.yaml, Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.Stage.yaml, Packages/Sites/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/Badge.fusion, Packages/Sites/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/BadgeGrid.fusion, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Main.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Molecules/_Badge.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/Badge.html, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/BadgeGrid.html, Packages/Sites/Neos.NeosIo/Resources/Public/JavaScript/Bundle.min.js, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css
Allows to add badge grids as container
for badges to show possible sponsoring
options for Neos.
Resolves: #155
=> TASK: Badge grid for sponsoring

Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Molecules/_ImageTeaser.scss, Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Molecules/_ReferencesList.scss, Packages/Sites/Neos.NeosIo/Resources/Public/JavaScript/Bundle.min.js, Packages/Sites/Neos.NeosIo/Resources/Public/Styles/Main.css
* Remove zoom effect
* Remove artifacts in safari
* Improve contrast between text and image
=> TASK: Improve rendering off showcase items

Packages/Sites/Neos.NeosIo/Configuration/NodeTypes.TeamListing.yaml, Packages/Sites/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/TeamListing.fusion, Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/TeamListing.html
This change adds the option to the team listing to show a specific group
additionally to showing all groups of a certain type.
=> FEATURE: Allow showing a specific crowd group

Packages/Sites/Neos.NeosIo/Resources/Private/Templates/NodeTypes/ReleasePlan.html
This updates the release schedule to the new cycle decided on in https://discuss.neos.io/t/rfc-an-adjusted-release-schedule-accepted/2746/3
=> TASK: Update the release schedule to match the new cycle

composer.lock
- Updating ocramius/package-versions (1.1.3) to ocramius/package-versions (1.2.0)
- Updating symfony/polyfill-mbstring (v1.5.0) to symfony/polyfill-mbstring (v1.6.0)
- Updating symfony/console (v2.8.27) to symfony/console (v2.8.32)
- Updating doctrine/annotations (v1.5.0) to doctrine/annotations (v1.6.0)
- Updating doctrine/orm (v2.5.11) to doctrine/orm (v2.5.14)
- Updating neos/error-messages (4.2.3) to neos/error-messages (4.2.6)
- Updating neos/utility-mediatypes (4.2.3) to neos/utility-mediatypes (4.2.6)
- Updating neos/utility-files (4.2.3) to neos/utility-files (4.2.6)
- Updating neos/utility-objecthandling (4.2.3) to neos/utility-objecthandling (4.2.6)
- Updating symfony/yaml (v2.8.27) to symfony/yaml (v2.8.32)
- Updating symfony/dom-crawler (v2.8.27) to symfony/dom-crawler …
=> TASK: Updating Neos & dependencies (including require-dev)

.editorconfig
- Add `root = true`
- Add configuration for Sites.xml
- Set `indent_size`  to `2` for yml, package.json and .*rc files
- Set `indent_style` to `space` for yml and json files
=> BUGFIX: Update .editorconfig

composer.lock
Package operations: 0 installs, 50 updates, 0 removals
- Updating ocramius/package-versions (1.2.0) to ocramius/package-versions (1.3.0)
- Updating symfony/polyfill-mbstring (v1.6.0) to symfony/polyfill-mbstring (v1.7.0)
- Updating symfony/console (v2.8.33) to symfony/console (v2.8.34)
- Updating neos/error-messages (4.3.2) to neos/error-messages (4.3.3)
- Updating neos/utility-mediatypes (4.3.2) to neos/utility-mediatypes (4.3.3)
- Updating neos/utility-files (4.3.2) to neos/utility-files (4.3.3)
- Updating neos/utility-objecthandling (4.3.2) to neos/utility-objecthandling (4.3.3)
- Updating symfony/yaml (v2.8.33) to symfony/yaml (v2.8.34)
- Updating symfony/dom-crawler (v2.8.33) to symfony/dom-crawler (v2.8.34)
- Updating neos/utility-unicode (4.3.2) to neos/utility-unicode (4.3.3)
- …
=> TASK: Update Neos 3.3.3 to 3.3.4, Neos UI 1.0.4 to 1.0.7

composer.lock
- Updating symfony/console (v2.8.34 => v2.8.35)
- Updating symfony/yaml (v2.8.34 => v2.8.35)
- Updating symfony/dom-crawler (v2.8.34 => v2.8.35)
- Updating ocramius/proxy-manager (2.1.1 => 2.2.0)
- Updating neos/media (3.3.6 => 3.3.7)
- Updating neos/fusion (3.3.6 => 3.3.7)
- Updating neos/content-repository (3.3.6 => 3.3.7)
- Updating neos/media-browser (3.3.6 => 3.3.7)
- Updating neos/diff (3.3.6 => 3.3.7)
- Updating neos/neos (3.3.6 => 3.3.7)
- Updating neos/nodetypes-basemixins (3.3.6 => 3.3.7)
- Updating neos/nodetypes-navigation (3.3.6 => 3.3.7)
- Updating neos/nodetypes-html (3.3.6 => 3.3.7)
- Updating neos/nodetypes-form (3.3.6 => 3.3.7)
- Updating neos/nodetypes-contentreferences (3.3.6 => 3.3.7)
- Updating neos/nodetypes-columnlayouts (3.3.6 => 3.3.7)
- Updating …
=> TASK: Update Neos to 3.3.7 and Neos.Neos.Ui to 1.0.8

composer.lock
- Updating symfony/console (v2.8.34 => v2.8.35)
- Updating symfony/yaml (v2.8.34 => v2.8.35)
- Updating symfony/dom-crawler (v2.8.34 => v2.8.35)
- Updating ocramius/proxy-manager (2.1.1 => 2.2.0)
- Updating neos/media (3.3.4) to neos/media (3.3.7)
- Updating neos/fusion (3.3.4) to neos/fusion (3.3.7)
- Updating neos/content-repository (3.3.4) to neos/content-repository (3.3.7)
- Updating neos/media-browser (3.3.4) to neos/media-browser (3.3.7)
- Updating neos/diff (3.3.4) to neos/diff (3.3.7)
- Updating neos/neos (3.3.4) to neos/neos (3.3.7)
- Updating neos/nodetypes-basemixins (3.3.4) to neos/nodetypes-basemixins (3.3.7)
- Updating neos/nodetypes-navigation (3.3.4) to neos/nodetypes-navigation (3.3.7)
- Updating neos/nodetypes-html (3.3.4) to neos/nodetypes-html (3.3.7)
- Updating …
=> TASK: Update Neos 3.3.4 to 3.3.7 and UI 1.0.7 to 1.0.8

Packages/Sites/Neos.NeosIo/composer.json, composer.json, composer.lock
=> FEATURE: Add gallery

src/Neos.NeosConIo/Resources/Private/Scss/Main.scss
Minor style adjustments to the teaser-video.
=> TASK: Add margin to teaser-video and resize to full width

src/Neos.NeosConIo/Resources/Private/Content/Sites.xml, src/Neos.NeosIo/Configuration/NodeTypes.ImageTeaser.yaml, src/Neos.NeosIo/Configuration/NodeTypes.Stage.yaml, src/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/ImageTeaser.fusion, src/Neos.NeosIo/Resources/Private/Scss/Molecules/_ImageTeaser.scss, src/Neos.NeosIo/Resources/Private/Templates/NodeTypes/ImageTeaser.html, src/Neos.NeosIo/Resources/Private/Templates/NodeTypes/Reference.List.Item.html
Template split was necessary because image teaser should either be a link or a div
=> FEATURE: Split template of image teaser, add hover styles

src/Neos.NeosConIo/Configuration/NodeTypes.SpeakerList.yaml, src/Neos.NeosConIo/Configuration/NodeTypes.TalkList.yaml, src/Neos.NeosConIo/Configuration/NodeTypes.Talks.yaml, src/Neos.NeosConIo/Resources/Private/Fusion/Documents/Speakers.fusion, src/Neos.NeosConIo/Resources/Private/Fusion/Documents/Talk.fusion, src/Neos.NeosConIo/Resources/Private/Fusion/Documents/Talks.fusion, src/Neos.NeosConIo/Resources/Private/Fusion/FusionObjects/SpeakerList.fusion, src/Neos.NeosConIo/Resources/Private/Fusion/FusionObjects/TalkList.fusion, src/Neos.NeosConIo/Resources/Private/Scss/Organisms/_Speaker.scss, src/Neos.NeosConIo/Resources/Private/Scss/Organisms/_Talk.scss, src/Neos.NeosConIo/Resources/Private/Templates/NodeTypes/Talk.html
Add NodeTypes for SpeakerList and TalkList. Additionally change styling for speaker teaser hover.
=> TASK: Change speaker and talk overview sites to editable sites

composer.json, composer.lock, src/Neos.FlowNeosIo/composer.json, src/Neos.NeosConIo/composer.json, src/Neos.NeosIo.Event/composer.json, src/Neos.NeosIo/composer.json
This change also updates the dependency structure
to allow composer update work correctly.
Resolves: #226
=> BUGFIX: Use compatible moc/notfound version

src/Neos.NeosIo/Classes/Neos/NeosIo/Fusion/DocumentationPageSubMenuImplementation.php, src/Neos.NeosIo/Resources/Private/Fusion/FusionObjects/DocumentationPageSubMenu.fusion, src/Neos.NeosIo/Resources/Private/Scss/Molecules/_SecondaryMenu.scss, src/Neos.NeosIo/Resources/Private/Templates/FusionObjects/DocumentationPageSubMenu.html, src/Neos.NeosIo/Resources/Public/Styles/Main.css
Fixed and improved the documentation page submenu, which was introduced with https://github.com/neos/Neos.NeosIo/pull/206
=> Documentation page

src/Neos.NeosConIo/Configuration/NodeTypes.Speakers.yaml, src/Neos.NeosConIo/Resources/Private/Fusion/Documents/Speaker.fusion, src/Neos.NeosConIo/Resources/Private/Fusion/Documents/Talk.fusion, src/Neos.NeosConIo/Resources/Private/Scss/Main.scss, src/Neos.NeosConIo/Resources/Private/Scss/Organisms/_SiteHeader.scss, src/Neos.NeosConIo/Resources/Private/Scss/Organisms/_Speaker.scss, src/Neos.NeosConIo/Resources/Private/Templates/NodeTypes/Speaker.html, src/Neos.NeosConIo/Resources/Private/Templates/NodeTypes/Talk.html, src/Neos.NeosIo/Resources/Private/Scss/Molecules/_ImageTeaser.scss
Add hover and active link styling for navbar, add focus for image teaser, change speakers overview to page, hide related talks and more tolks when no talk is selected
=> TASK: Some styling changes and fixes

src/Neos.NeosIo/Resources/Private/Templates/NodeTypes/ReleasePlan.html
=> TASK: Add releases up to 5.3 / 6.3 to the release plan

.beach.yaml, build.sh
To make them executable manually via
./build.sh
=> TASK: Extract build steps to shell script

DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.Disabled.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.Event.List.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.Event.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.EventArchive.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.SemanticSection.yaml, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.DatesString.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.List.Item.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.List.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Documents/Page/Event.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Documents/Page/EventArchive.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/Event.List.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Main.scss, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Molecules/_Event.scss, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Molecules/_EventList.scss, DistributionPackages/Neos.NeosIo/Resources/Public/Neos.NeosIo, composer.json, composer.lock
=> FEATURE: Node based events

DistributionPackages/Neos.NeosIo/Classes/Eel/Helper/EventHelper.php, DistributionPackages/Neos.NeosIo/Configuration/Settings.yaml, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.List.Item.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.List.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Event.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Documents/Page/EventArchive.fusion
* Render optional event details only if they are set
* Fix "no entries notice" on EventArchive pages
* Group events by month
Fixes: #271
=> Improve events pages

DistributionPackages/Neos.NeosIo/Resources/Private/Templates/NodeTypes/FundingBadges.html
=> BUGFIX: Don`t render amount of money for active member badges

DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.ServiceProvider.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.ServiceProviderCollection.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.ServiceType.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Mixin.Contributions.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Override.Document.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/Settings.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Components/MapData.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Components/ProviderList.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Documents/ServiceProvider.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Documents/ServiceProviderCollection.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Main.js, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Main.tsx, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Components/ProviderListEntry.tsx, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Context/ProviderData.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Helper/Capitalize.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Helper/Shuffle.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Helper/Sorter.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Interfaces/Provider.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/MarkerClusters.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/ProviderListing.tsx, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/index.js, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/index.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Scss/Main.scss, babel.config.js, package.json, tsconfig.json, webpack.config.ts, webpack.packages.ts, yarn.lock
Further improvements to layout and functionality
=> TASK: Service provider listing

DistributionPackages/Neos.NeosIo/composer.json, composer.lock
Partially fix for #292. The script tag will only be included if an accoring nodeType is in use. GoEssential is working on the actual js bug
=> BUGFIX #292 update GoEssential package

DistributionPackages/Neos.MarketPlace/Classes/Property/TypeConverter/PackageConverter.php
This keeps the number of stars and downloads up-to-date
for packages without new releases.
Resolves: #312
=> FEATURE: Sync stale packages when metadata changes

DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.KeyvisualMixin.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.SemanticSection.yaml, DistributionPackages/Neos.NeosIo/composer.json, composer.lock
With this update we can use single vidos as well
=> TASK: introduce GoEssential video NodeType

DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Components/Provider.CaseStudies.fusion
Somebody forgot to implement this ...
=> FEATURE: Add rendering for referenced case studies in providers

webpack.config.ts, webpack.packages.ts
* Add inline option for generating CSS and JS files
Disable `.map` file on inline CSS files
Don't ask twice for source map
=> FEATURE: Add inline option for generating CSS and JS files

DistributionPackages/Neos.MarketPlace/Resources/Public/Assets/feed.xsl
=> BUGFIX: Override user specified background in xslt

DistributionPackages/Neos.MarketPlace/Classes/Eel/FlowQueryOperations/SortByPropertyOperation.php, DistributionPackages/Neos.MarketPlace/Resources/Private/Fusion/Components/Feed/PackageVersions.fusion, DistributionPackages/Neos.MarketPlace/Resources/Private/Fusion/Components/Feed/Version.fusion, DistributionPackages/Neos.MarketPlace/Resources/Private/Fusion/Documents/Feed.fusion, DistributionPackages/Neos.MarketPlace/Resources/Public/Assets/feed.xsl
* Sort all releases by time property
* Add repository link to summary
* Improve rendering structure
* Improve link titles in xslt
=> TASK: Improve package feed

DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.Post.yaml, DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.Stage.yaml
Solves
- https://github.com/neos/Neos.NeosIo/issues/357
- https://github.com/neos/Neos.NeosIo/issues/354
=> Few minor bugfixes

DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.CountUp.yaml
Solves https://github.com/neos/Neos.NeosIo/issues/327
=> Added Validators to countup, solves issue #327

DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/Fusion/ContentTypes/Reference.List.Item.fusion
=> BUGFIX: Set proper node in context for project volumes helper

DistributionPackages/Neos.NeosIo/Configuration/NodeTypes.RootPage.yaml
- Allow shortcut to cross-link pages
=> Improvements for handling GDPR

DistributionPackages/Neos.MarketPlace/Classes/Service/PackageConverter.php, DistributionPackages/Neos.MarketPlace/Configuration/Settings.yaml
There we index the node no matter if we have changes or not.
=> FEATURE: Re-enable marketplace indexing instead of realtimeIndexing

DistributionPackages/Neos.NeosIo.CaseStudies/Configuration/NodeTypes.Reference.yaml, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/Fusion/ContentTypes/CaseList.fusion, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/Fusion/Helper/ProjectVolumes.fusion, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/CaseStudyListing.tsx, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/Components/CaseStudyGridItem.tsx, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/Components/CaseStudyTableRow.tsx, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/Helper/ProjectVolume.ts
=> TASK: Properly interpret project volume in Fusion and JS

DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Content.AwardReference.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.Award.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.ServiceProvider.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Configuration/NodeTypes.Document.ServiceProviderCollection.yaml, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Components/Provider.Awards.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Content/AwardReference.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Documents/ServiceProvider.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Scss/Main.scss, package.json
After we deploy this change we have to run a node repair to add the new content collection to the service providers.
`flow node:repair --only createMissingChildNodes --node-type Neos.NeosIo.ServiceOfferings:Document.ServiceProvider`
=> FEATURE: Add structured data and awards to service providers

DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Components/ProviderList.fusion, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Components/ProviderListGridItem.tsx, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Components/ProviderListTableRow.tsx, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/JavaScript/Interfaces/Provider.ts, DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Scss/Main.scss
=> FEATURE: Show service provider awards in listing

DistributionPackages/Neos.MarketPlace/Classes/Domain/Model/Storage.php, DistributionPackages/Neos.MarketPlace/Classes/Service/PackageConverter.php, DistributionPackages/Neos.MarketPlace/Classes/Service/PackageImporter.php, DistributionPackages/Neos.MarketPlace/Configuration/NodeTypes.Package.yaml, DistributionPackages/Neos.MarketPlace/Resources/Private/Translations/en/NodeTypes/Package.xlf, composer.lock
Packages are not synced anymore if they only have new favs or download numbers.
At the latest a package is synced after 24h.
=> TASK: Improve sync

composer.lock
- Upgrading cocur/slugify (v4.1.0 => v4.2.0)
- Upgrading composer/composer (2.2.17 => 2.2.18)
- Upgrading doctrine/collections (1.6.8 => 1.7.2)
- Upgrading doctrine/event-manager (1.1.1 => 1.1.2)
- Upgrading flownative/google-cloudstorage (5.3.1 => 5.3.2)
- Upgrading google/auth (v1.21.1 => v1.22.0)
- Upgrading google/cloud-core (v1.46.1 => v1.47.2)
- Upgrading google/cloud-storage (v1.27.1 => v1.28.1)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
- Upgrading laminas/laminas-code (4.5.2 => 4.6.0)
- Upgrading monolog/monolog (2.7.0 => 2.8.0)
- Upgrading neos/cache (6.3.19 => 6.3.20)
- Upgrading neos/content-repository (5.3.12 => 5.3.13)
- Upgrading neos/diff (5.3.12 => 5.3.13)
- Upgrading neos/eel (6.3.19 => 6.3.20)
- Upgrading neos/error-messages (6.3.19 => 6.3.20)
- Upgrading …
=> TASK: Update to the latest version of Neos 5.3

DistributionPackages/Neos.MarketPlace/Migrations/ContentRepository/Version20221116160000.yaml, DistributionPackages/Neos.MarketPlace/Resources/Private/Fusion/FusionObjects/Package/PackageReadme.fusion, DistributionPackages/Neos.MarketPlace/Resources/Private/JavaScript/Components/ShowMore.js
- addition: fix condition evaluation in `Neos.MarketPlace:PackageReadme`
This bug is also present in https://github.com/neos/Neos.NeosIo/pull/455
=> BUGFIX: Add migration for renamed property in Neos.MarketPlace:Readme

DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/Fusion/ContentTypes/CaseList.fusion, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/Fusion/Main.tsx, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/CaseStudyListing.tsx, DistributionPackages/Neos.NeosIo.CaseStudies/Resources/Private/JavaScript/Components/CaseStudyTableRow.tsx
=> BUGFIX: Change case study sorting to launch date

DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Organisms/_KeyVisual.scss
* Remove text shadow
* Darken background image for large keyvisual
* Larger font for large keyvisual
* Full viewport height
Resolves: #492
=> FEATURE: Update header stage design

DistributionPackages/Neos.NeosIo/Classes/ContentRepository/Transformations/ChangeChildNodeTypeTransformation.php, DistributionPackages/Neos.NeosIo/Classes/ContentRepository/Transformations/FlattenCollectionsTransformation.php, DistributionPackages/Neos.NeosIo/Migrations/TYPO3CR/Version20230725171922.yaml, DistributionPackages/Neos.NeosIo/NodeTypes/Content/Button.yaml, DistributionPackages/Neos.NeosIo/NodeTypes/Content/Column.yaml, DistributionPackages/Neos.NeosIo/NodeTypes/Mixins/ButtonStyles.yaml, DistributionPackages/Neos.NeosIo/NodeTypes/Override/MultiColumn.yaml, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/Button.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Content/Column.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/NodeTypes/MultiColumn.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Overrides/Image.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Molecules/_Grid.scss, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Molecules/_Image.scss, DistributionPackages/Neos.NeosIo/Resources/Private/Scss/Organisms/_Stage.scss
Resolves: #494 
Required the following migration
```console
./flow node:migrate --version 20230725171922
```
=> FEATURE: Multi column elements with links

.ddev/commands/web/flow
Allows to execute flow command with ddev flow [...] without logging into ddev container (ddev ssh)
=> Adding flow command for ddev

DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Atom/Text/Paragraph.fusion, DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Module/TextAndImage.fusion
=> Rebrand image and text

DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Molecule/HighlightBoxes/HighlightBoxes.Box.fusion, DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Molecule/HighlightBoxes/HighlightBoxes.fusion
https://github.com/orgs/neos/projects/53/views/1?pane=issue&itemId=53979688
=> TASK: Add HighlightBoxes with box item

DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Molecule/StepByStepHighlight/StepByStepHighlight.Step.fusion, DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Molecule/StepByStepHighlight/StepByStepHighlight.fusion
Step-by-Step Highlight component: https://github.com/orgs/neos/projects/53/views/1?pane=issue&itemId=53977279
=> TASK: Add Step-by-Step Highlight component with entries

DistributionPackages/Neos.Presentation/Resources/Private/Fusion/Module/TextAndImage.fusion
Finetuning TextAndImage component
=> TASK: finetuning image

DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Components/SiteFooter.fusion
This allows to apply for a sponsored UptimeRobot plan… it looks like this:
=> TASK: Add UptimeRobot link in SiteFooter.fusion

DistributionPackages/Neos.NeosIo.FeatureList/NodeTypes/Content/Feature.yaml, DistributionPackages/Neos.NeosIo.FeatureList/NodeTypes/Content/FeatureGroup.yaml, DistributionPackages/Neos.NeosIo.FeatureList/composer.json, DistributionPackages/Neos.NeosIo.ServiceOfferings/composer.json, DistributionPackages/Neos.NeosIo/Configuration/Settings.Presets.yaml, DistributionPackages/Neos.NeosIo/composer.json, composer.lock
Sitegeist.Silhouettes is discontinued in favor of property presets in the Neos core. This change adjusts that and removes the dependency.
=> TASK: Remove the dependency to sitegeist silhouettes that was integrated into the Neos core

.localbeach.dist.env, composer.json, composer.lock
=> TASK: Upgrade to Neos 8.3.18

Configuration/Production/Beach/Instance/Settings.yaml
Currently Imagick seems to have better performance…
=> TASK: Drop use of vips for image handling

DistributionPackages/Neos.NeosIo/Configuration/Settings.CodeView.yaml, DistributionPackages/Neos.NeosIo/NodeTypes/Override/Code.yaml, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Overrides/CodeView.fusion, DistributionPackages/Neos.NeosIo/Resources/Private/Fusion/Overrides/Page.fusion, DistributionPackages/Neos.NeosIo/composer.json, composer.lock
With this fix, code views can be added again and the 2-3 slowqueries on every page are resolved.
=> BUGFIX: Resolve performance and UX issues with codeviews
